// <auto-generated />
namespace KudoCinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddMovieAndGenreModel_5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMovieAndGenreModel_5));
        
        string IMigrationMetadata.Id
        {
            get { return "202004250343374_AddMovieAndGenreModel_5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
